DROP TABLE IF EXISTS USER_INF;
CREATE TABLE USER_INF(id INTEGER PRIMARY KEY, name VARCHAR(100), sex VARCHAR(2));
INSERT INTO USER_INF VALUES(1, 'xingchuan.qxc', '男');
INSERT INTO USER_INF VALUES(2, 'Jevin.Q', '男');
INSERT INTO USER_INF VALUES(3, 'Allen', '男');
INSERT INTO USER_INF VALUES(4, 'Ivy', '女');
INSERT INTO USER_INF VALUES(5, 'Shine', '女');
